VIM switch to a different merge-po-files script

diff --git a/bin/merge-po-files b/bin/merge-po-files
--- a/bin/merge-po-files
+++ b/bin/merge-po-files
@@ -1,109 +1,115 @@
 #!/bin/bash
-# git merge driver for .PO files
-# Copyright (c) Mikko Rantalainen <mikko.rantalainen@peda.net>, 2013
-# License: MIT
+# A git merge driver for repos with translations and i18n, the driver helps
+# resolve .po file conflicts when merging or rebasing gettext catalogs.
+# https://github.com/beck/git-po-merge
+set -eu
 
-ORIG_HASH=$(git hash-object "${1}")
-WORKFILE=$(git ls-tree -r HEAD | grep -F "$ORIG_HASH" | cut -b54-)
-echo "Using custom merge driver for $WORKFILE..."
-
-LOCAL="${1}._LOCAL_"
-BASE="${2}._BASE_"
-REMOTE="${3}._REMOTE_"
-
-LOCAL_ONELINE="$LOCAL""ONELINE_"
-BASE_ONELINE="$BASE""ONELINE_"
-REMOTE_ONELINE="$REMOTE""ONELINE_"
-
-OUTPUT="$LOCAL""OUTPUT_"
-MERGED="$LOCAL""MERGED_"
-MERGED2="$LOCAL""MERGED2_"
-
-TEMPLATE1="$LOCAL""TEMPLATE1_"
-TEMPLATE2="$LOCAL""TEMPLATE2_"
-FALLBACK_OBSOLETE="$LOCAL""FALLBACK_OBSOLETE_"
-
-# standardize the input files for regexping
-# default to UTF-8 in case charset is still the placeholder "CHARSET"
-cat "${1}" | perl -npe 's!(^"Content-Type: text/plain; charset=)(CHARSET)(\\n"$)!$1UTF-8$3!' | msgcat --no-wrap --sort-output - > "$LOCAL"
-cat "${2}" | perl -npe 's!(^"Content-Type: text/plain; charset=)(CHARSET)(\\n"$)!$1UTF-8$3!' | msgcat --no-wrap --sort-output - > "$BASE"
-cat "${3}" | perl -npe 's!(^"Content-Type: text/plain; charset=)(CHARSET)(\\n"$)!$1UTF-8$3!' | msgcat --no-wrap --sort-output - > "$REMOTE"
-
-# convert each definition to single line presentation
-# extra fill is required to make sure that git separates each conflict 
-perl -npe 'BEGIN {$/ = "\n\n"}; s/#\n$/\n/s; s/#/##/sg; s/\n/#n/sg; s/#n$/\n/sg; s/#n$/\n/sg; $_.="#fill#\n" x 4' "$LOCAL" > "$LOCAL_ONELINE"
-perl -npe 'BEGIN {$/ = "\n\n"}; s/#\n$/\n/s; s/#/##/sg; s/\n/#n/sg; s/#n$/\n/sg; s/#n$/\n/sg; $_.="#fill#\n" x 4' "$BASE"  > "$BASE_ONELINE"
-perl -npe 'BEGIN {$/ = "\n\n"}; s/#\n$/\n/s; s/#/##/sg; s/\n/#n/sg; s/#n$/\n/sg; s/#n$/\n/sg; $_.="#fill#\n" x 4' "$REMOTE"  > "$REMOTE_ONELINE"
-
-# merge files using normal git merge machinery
-git merge-file -p --union -L "Current (working directory)" -L "Base (common ancestor)" -L "Incoming (applied changeset)" "$LOCAL_ONELINE" "$BASE_ONELINE" "$REMOTE_ONELINE" > "$MERGED"
-MERGESTATUS=$?
-
-# remove possibly duplicated headers (workaround msguniq bug http://comments.gmane.org/gmane.comp.gnu.gettext.bugs/96)
-cat "$MERGED" | perl -npe 'BEGIN {$/ = "\n\n"}; s/^([^\n]+#nmsgid ""#nmsgstr ""#n.*?\n)([^\n]+#nmsgid ""#nmsgstr ""#n.*?\n)+/$1/gs' > "$MERGED2"
-
-# remove lines that have totally empty msgstr
-# and convert back to normal PO file representation
-cat "$MERGED2" | grep -v '#nmsgstr ""$' | grep -v '^#fill#$' | perl -npe 's/#n/\n/g; s/##/#/g' > "$MERGED"
-
-# run the output through msguniq to merge conflicts gettext style
-# msguniq seems to have a bug that causes empty output if zero msgids
-# are found after the header. Expected output would be the header...
-# Workaround the bug by adding an empty obsolete fallback msgid
-# that will be automatically removed by msguniq
-
-cat > "$FALLBACK_OBSOLETE" << 'EOF'
-
-#~ msgid "obsolete fallback"
-#~ msgstr ""
-
-EOF
-cat "$MERGED" "$FALLBACK_OBSOLETE" | msguniq --no-wrap --sort-output > "$MERGED2"
-
-
-# create a hacked template from default merge between 3 versions
-# we do this to try to preserve original file ordering
-msgcat --use-first "$LOCAL" "$REMOTE" "$BASE" > "$TEMPLATE1"
-msghack --empty "$TEMPLATE1" > "$TEMPLATE2"
-msgmerge --silent --no-wrap --no-fuzzy-matching "$MERGED2" "$TEMPLATE2" > "$OUTPUT"
-
-# show some results to stdout
-if grep -q '#-#-#-#-#' "$OUTPUT"
+# if additional options are ever added will need to use getopts
+silent=false
+if [ ${1:-loud} = '-s' ]
 then
-    FUZZY=$(cat "$OUTPUT" | msgattrib --only-fuzzy --no-obsolete --color | perl -npe 'BEGIN{ undef $/; }; s/^.*?msgid "".*?\n\n//s')
-    if test -n "$FUZZY"
-    then
-        echo "-------------------------------"
-        echo "Fuzzy translations after merge:"
-        echo "-------------------------------"
-        echo "$FUZZY"
-        echo "-------------------------------"
-    fi
+  silent=true
+  shift
 fi
 
-# git merge driver must overwrite the first parameter with output
-mv "$OUTPUT" "${1}"
+if [ $# -ne 3 ]
+then
+  echo "usage: git-po-merge [-s] our.po base.po their.po"
+  exit 1
+fi
 
-# cleanup
-rm -f "$LOCAL" "$BASE" "$REMOTE" "$LOCAL_ONELINE" "$BASE_ONELINE" "$REMOTE_ONELINE" "$MERGED" "$MERGED2" "$TEMPLATE1" "$TEMPLATE2" "$FALLBACK_OBSOLETE"
+ours=$1
+base=$2
+theirs=$3
 
-# return conflict if merge has conflicts according to msgcat/msguniq
-grep -q '#-#-#-#-#' "${1}" && exit 1
 
-# otherwise, return git merge status
-exit $MERGESTATUS
+function log {
+  if [ $silent = false ]
+  then
+    echo "$@"
+  fi
+}
 
-# Steps to install this driver:
-# (1) Edit ".git/config" in your repository directory
-# (2) Add following section:
-#
-# [merge "merge-po-files"]
-#   name = merge po-files driver
-#   driver = ./bin/merge-po-files %A %O %B
-#   recursive = binary
-#
-# or
-#
-# git config merge.merge-po-files.driver "./bin/merge-po-files %A %O %B"
-#
-# The file ".gitattributes" will point git to use this merge driver.
+function elog {
+  log "$@" >&2
+}
+
+function verify_msgcat {
+  if ! $(msgcat --version > /dev/null 2>&1)
+  then
+    elog
+    elog "ERROR in git-po-merge: msgcat is not found."
+    elog "  Installing gettext should include msgcat."
+    elog "  Falling back to three way merge."
+    elog
+    git merge-file -L "ours" -L "base" -L "theirs" "$ours" "$base" "$theirs"
+    exit 1
+  fi
+}
+
+function get_langheader {
+    grep -m 1 -e '^\"Language:\s.*\\n\"$' "$ours"
+}
+
+function get_pluralheader {
+    grep -m 1 -e '^\"Plural-Forms:\s.*\\n\"$' "$ours"
+}
+
+function resolvepo {
+  log -n "Resolving po conflict with git-merge-po... "
+  local merge_opts="--sort-output --no-location --width=80"
+  local headerpo=$(mktemp -t headers.XXXXXX.po)
+  local temp=$(mktemp -t temp.XXXXXX.po)
+
+  # fix gettext nonsense and noise from 3rd party tools
+  local noise="-e /^#.Generated.by.grunt.*/d"
+  noise="$noise -e s/charset=CHARSET/charset=UTF-8/"
+  cp "$ours" "$temp" && sed $noise "$temp" > "$ours"
+  cp "$base" "$temp" && sed $noise "$temp" > "$base"
+  cp "$theirs" "$temp" && sed $noise "$temp" > "$theirs"
+
+  # reduce all three to a single file
+  msgcat "$base" "$ours" "$theirs" $merge_opts --output-file="$temp"
+
+  # set a minimalist header
+  echo 'msgid ""' >> "$headerpo"
+  echo 'msgstr ""' >> "$headerpo"
+  echo '"Content-Type: text/plain; charset=UTF-8\n"' >> "$headerpo"
+  echo '"MIME-Version: 1.0\n"' >> "$headerpo"
+  echo "$(get_langheader)" >> "$headerpo"
+  echo "$(get_pluralheader)" >> "$headerpo"
+
+  msgcat "$headerpo" "$temp" --use-first $merge_opts --output-file="$ours"
+
+  # cleanup
+  rm -rf "$temp" "$headerpo"
+}
+
+
+function rename_conflict_titles {
+  # replace tempfile names with "ours", "theirs", "base"
+  # msgcat shows confilcts using delimiter comments like:
+  # #-#-#-#-#  .merge_file_IE83XW  #-#-#-#-#
+  local temp=$(mktemp -t temp.XXXXXX.po)
+  sed -e "s|$ours|ours|" -e "s|$theirs|theirs|" -e "s|$base|base|" "$ours" > "$temp"
+  mv "$temp" "$ours"
+}
+
+
+function check_for_conflicts {
+  # check if msgcat conflict comments are present
+  if $(grep --silent "#-#-#-#-#" "$ours")
+  then
+    elog
+    elog "CONFLICT, search for '#-#-#-#-#' in the po files."
+    elog
+    exit 1
+  else
+    log "done."
+  fi
+}
+
+verify_msgcat
+resolvepo
+rename_conflict_titles
+check_for_conflicts
